### ISSUE TITLE
[Feature Request] Serializable structs.

### ISSUE THREAD

**Issue by dkromhof** [MRDavidYen/axum-error-handler#1]
Awesome crate. Looking for something like this, I am currently modifying it so I can have custom structs as json serializable into ur macro.

I will do a pull request, if I have something. But, seeing this feature in general would be very nice, if it's even remotely feasible and fits the use case of this crate.

**Comment by MRDavidYen** [comment]
Thanks for your feedback.

As you said, this crate just has limited feature to parse enum to Axum Response right now.
I am planing to add a customize macros function attribute on Enum that allow user custom their own Response.

Maybe something like this:
```rust
#[derive(Debug, Error, AxumErrorResponse)]
#[axum_error_response(customize_fn = "user_own_response")]
    pub enum TestError {
        #[error("Bad request: {0}")]
        #[status_code("400")]
        #[code("BAD_REQUEST")]
        BadRequest(String),
        #[error("Internal server error {0}")]
        #[status_code("500")]
        #[code("INTERNAL_SERVER_ERROR")]
        AnotherNoStringError(#[from] InnerError),
    }

   fn user_own_resposne(error: axum_error_handler::ErrorExpose) -> Reponse {
   }
```

And feel free to discuss and create PR on this repo. Thank you.
